{"uid":"8b93e871e9d47e92","name":"openNewAccountTest","fullName":"Tests.NewAccountTest.openNewAccountTest","historyId":"52a544ee2d2894e4c7c747db99b9af10","time":{"start":1759448523273,"stop":1759448523289,"duration":16},"status":"broken","statusMessage":"\n[public void Tests.NewAccountTest.openNewAccountTest(java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).\nData provider mismatch\nMethod: openNewAccountTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])\nArguments: [(java.lang.String) Checking,(java.lang.String) 12345]","statusTrace":"org.testng.internal.reflect.MethodMatcherException: \n[public void Tests.NewAccountTest.openNewAccountTest(java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).\nData provider mismatch\nMethod: openNewAccountTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])\nArguments: [(java.lang.String) Checking,(java.lang.String) 12345]\r\n\tat org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)\r\n\tat org.testng.internal.Parameters.injectParameters(Parameters.java:915)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":3,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"package","value":"Tests.NewAccountTest"},{"name":"testClass","value":"Tests.NewAccountTest"},{"name":"testMethod","value":"openNewAccountTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"ParaBank"},{"name":"subSuite","value":"Tests.NewAccountTest"},{"name":"host","value":"DESKTOP-JS56419"},{"name":"thread","value":"17996@DESKTOP-JS56419.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"132e4efc15b0fcb0","status":"broken","statusDetails":"\n[public void Tests.NewAccountTest.openNewAccountTest(java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).\nData provider mismatch\nMethod: openNewAccountTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])\nArguments: [(java.lang.String) Checking,(java.lang.String) 12345]","time":{"start":1759448494169,"stop":1759448494176,"duration":7}},{"uid":"df20b60be49cb0a8","status":"broken","statusDetails":"java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1","time":{"start":1759448428217,"stop":1759448428231,"duration":14}},{"uid":"99c259091bb15712","status":"broken","statusDetails":"java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1","time":{"start":1759448405630,"stop":1759448405640,"duration":10}}],"categories":[{"name":"Test defects","matchedStatuses":[]}],"tags":[]},"source":"8b93e871e9d47e92.json","parameterValues":[]}